apiVersion: v1
kind: LimitRange
metadata:
  name:
  namespace:
spec:
  limits:
    - type: Container
      min:
        cpu:
        memory:
      max:
        cpu:
        memory:
      default:
        cpu:
        memory:
      defaultRequest:
        cpu:
        memory:


