apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: 
  namespace: 
spec:
  targetRef:
    apiVersion: apps/v1
    kind:
    name: 
  updatePolicy:
    updateMode: ""
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: 50m
        memory: 60Mi
      maxAllowed:
        cpu: 200m
        memory: 125Mi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

