apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: 
  namespace: 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: 
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Pods
      pods:
        metric:
          name: messages_processed_per_second
        target:
          type: AverageValue
          averageValue: 10
