apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.9.1
          ports:
            - containerPort: 9100
              name: nginx
          resources:
            requests:
              cpu: 100m
              memory: 125Mi
            limits:
              cpu: 200m
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 9100
      targetPort: nginx
      name: metrics
  type: NodePort

