apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor
  namespace: nginx
  labels:
    prometheus: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    matchNames:
      - nginx
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s

