apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace: 
  labels:
    app: 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.9.1
          ports:
            - containerPort: 9100
              name: 
          resources:
            requests:
              cpu: 100m
              memory: 125Mi
            limits:
              cpu: 200m
              memory: 175Mi
          livenessProbe:
            httpGet:
              port: 9100
              path: /metrics
            initalDelaySeconds:
            periodSeconds:
            timeoutSeconds:
            failureThshold:
          readinressProbe:
            httpGet:
              port: 9100
              path: /metrics
            initalDelaySeconds:
            periodSeconds:
            successThshold:
            failureThshold:

---
apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: 
  labels:
    app: 
spec:
  selector:
    app: 
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 
      name: 
  type: ClusterIP

