apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
  namespace: 
  labels:
    app: 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
        - name: 
          image: 
          ports:
            - containerPort:
              name: 
          resources:
            requests:
              cpu: 100m
              memory: 125mi
            limits:
              cpu: 500m
              memory: 325mi
          livenessProbe:
            tcpSocket:
              port:
            initalDelaySeconds:
            periodSeconds:
            timeoutSeconds:
            failureThshold:
          readinressProbe:
            tcpSocket:
              port:
            initalDelaySeconds:
            periodSeconds:
            successThshold:
            failureThshold:
---
apiVersion: v1
kind: Service
metadata:
  name: 
  namespace: 
  labels:
    app: 
spec:
  selector:
    app: 
  ports:
    - protocol: TCP
      port: 
      targetPort: 
  type: ClusterIP

